[package]
name = "cage-target-cpp"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
description = "C++ code generator for Cage"

[dependencies]
cage-core = { path = "../cage-core" }
cage-target-template = { path = "../cage-target-template" }
serde_json = { workspace = true }

[dev-dependencies]
indexmap = { workspace = true }
serde_yaml = { workspace = true }
